[package]
name = "streaming_server_app"
version = "0.1.0"
description = "A peer to peer streaming service"
authors = ["Massimiliano Baglioni"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.9.5", features = [] }
tauri-plugin-log = "2"
streaming_server = { path = "../" }
tracing-subscriber = "0.3.22"
tracing = "0.1.44"
raw-window-handle = "0.6.2"
iroh-tickets = "1.0.0"
iroh = "1.0.0"
tokio = "1.49.0"
tauri-plugin-clipboard-manager = "2"
anyhow = "1.0.102"
tokio-util = "0.7.19"

[target.'cfg(target_os = "windows")'.dependencies]
windows-future = "0.3.2"
windows = { version = "0.62.2", features = [
    "Graphics_Capture",
    "Graphics_DirectX",
    "Graphics_DirectX_Direct3D11",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_System_WinRT_Graphics_Capture",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_System_Com"
] }
